
import '../api_responce_model/para_model.dart';

List<JuzModel> juzList = [
  JuzModel(juzNumber: 1, juzName: "Alif Lam Meem", start: "1. Al-Fatiha Verse 1", end: "2. Al-Baqarah Verse 141", juzArabicname: 'الٓمٓ'),
  JuzModel(juzNumber: 2, juzName: "Sayaqool", start: "2. Al-Baqarah Verse 142", end: "2. Al-Baqarah Verse 252", juzArabicname: 'سَيَقُولُ'),
  JuzModel(juzNumber: 3, juzName: "Tilkal Rusul", start: "2. Al-Baqarah Verse 253", end: "3. Al-Imran Verse 92", juzArabicname: 'تِلْكَ ٱلرُّسُلُ'),
  JuzModel(juzNumber: 4, juzName: "Lan Tana Loo", start: "3. Al-Imran Verse 93", end: "4. An-Nisa Verse 23", juzArabicname: 'لَن تَنَالُو'),
  JuzModel(juzNumber: 5, juzName: "Wal Mohsanat", start: "4. An-Nisa Verse 24", end: "4. An-Nisa Verse 147", juzArabicname: 'وَٱلْمُحْصَنَـٰتُ'),
  JuzModel(juzNumber: 6, juzName: "La Yuhibbullah", start: "4. An-Nisa Verse 148", end: "5. Al-Ma’idah Verse 81", juzArabicname: 'لَّا يُحِبُّ ٱللَّهُ'),
  JuzModel(juzNumber: 7, juzName: "Wa Iza Samiu", start: "5. Al-Ma’idah Verse 82", end: "6. Al-An’am Verse 110", juzArabicname: 'وَإِذَا سَمِعُو'),
  JuzModel(juzNumber: 8, juzName: "Wa Lau Annana", start: "6. Al-An’am Verse 111", end: "7. Al-A’raf Verse 87", juzArabicname: 'وَلَوْ أَنَّنَا'),
  JuzModel(juzNumber: 9, juzName: "Qalal Malao", start: "7. Al-A’raf Verse 88", end: "8. Al-Anfal Verse 40", juzArabicname: 'قَالَ ٱلْمَلَأُ'),
  JuzModel(juzNumber: 10, juzName: "Wa A’lamu", start: "8. Al-Anfal Verse 41", end: "9. At-Tauba Verse 92", juzArabicname: 'وَٱعْلَمُوٓ'),
  JuzModel(juzNumber: 11, juzName: "Yatazeroon", start: "9. At-Tauba Verse 93", end: "11. Hud Verse 5", juzArabicname: 'يَعْتَذِرُونَ'),
  JuzModel(juzNumber: 12, juzName: "Wa Mamin Da’abat", start: "11. Hud Verse 6", end: "12. Yusuf Verse 52", juzArabicname: 'وَمَا مِن دَآبَّةٍۢ'),
  JuzModel(juzNumber: 13, juzName: "Wa Ma Ubrioo", start: "12. Yusuf Verse 53", end: "14. Ibrahim Verse 52", juzArabicname: 'وَمَآ أُبَرِّئُ'),
  JuzModel(juzNumber: 14, juzName: "Rubama", start: "15. Al-Hijr Verse 1", end: "16. An-Nahl Verse 128", juzArabicname: 'رُّبَمَا'),
  JuzModel(juzNumber: 15, juzName: "Subhanallazi", start: "17. Al-Isra Verse 1", end: "18. Al-Kahf Verse 74", juzArabicname: 'سُبْحَـٰنَ ٱلَّذِىٓ'),
  JuzModel(juzNumber: 16, juzName: "Qal Alam", start: "18. Al-Kahf Verse 75", end: "20. Ta-Ha Verse 135", juzArabicname: 'قَالَ أَلَمْ أَقُل'),
  JuzModel(juzNumber: 17, juzName: "Aqtarabo", start: "21. Al-Anbiya Verse 1", end: "22. Al-Hajj Verse 78", juzArabicname: 'ٱقْتَرَبَ لِلنَّاسِ'),
  JuzModel(juzNumber: 18, juzName: "Qadd Aflaha", start: "23. Al-Muminun Verse 1", end: "25. Al-Furqan Verse 20", juzArabicname: 'قَدْ أَفْلَحَ '),
  JuzModel(juzNumber: 19, juzName: "Wa Qalallazina", start: "25. Al-Furqan Verse 21", end: "27. An-Naml Verse 55", juzArabicname: 'وَقَالَ ٱلَّذِينَ'),
  JuzModel(juzNumber: 20, juzName: "A’man Khalaq", start: "27. An-Naml Verse 56", end: "29. Al-Ankabut Verse 45", juzArabicname: 'أَمَّنْ خَلَقَ'),
  JuzModel(juzNumber: 21, juzName: "Utlu Ma Oo’hi", start: "29. Al-Ankabut Verse 46", end: "33. Al-Ahzab Verse 30", juzArabicname: 'ٱتْلُ مَآ أُوحِىَ'),
  JuzModel(juzNumber: 22, juzName: "Wa Manyaqnut", start: "33. Al-Ahzab Verse 31", end: "36. Ya-Sin Verse 27", juzArabicname: 'وَمَن يَقْنُتْ'),
  JuzModel(juzNumber: 23, juzName: "Wa Mali", start: "36. Ya-Sin Verse 28", end: "39. Az-Zumar Verse 31", juzArabicname: 'وَمَا لِىَ'),
  JuzModel(juzNumber: 24, juzName: "Faman Azlam", start: "39. Az-Zumar Verse 32", end: "41. Fussilat Verse 46", juzArabicname: 'فَمَنْ أَظْلَمُ'),
  JuzModel(juzNumber: 25, juzName: "Elahe Yuruddo", start: "41. Fussilat Verse 47", end: "45. Al-Jathiyah Verse 37", juzArabicname: 'إِلَيْهِ يُرَدُّ'),
  JuzModel(juzNumber: 26, juzName: "Ha’a Meem", start: "46. Al-Ahqaf Verse 1", end: "51. Az-Dhariyat Verse 30", juzArabicname: 'حمٓ'),
  JuzModel(juzNumber: 27, juzName: "Qala Fama Khatbukum", start: "51. Az-Dhariyat Verse 31", end: "57. Al-Hadid Verse 29", juzArabicname: 'قَالَ فَمَا خَطْبُكُمْ'),
  JuzModel(juzNumber: 28, juzName: "Qadd Sami Allah", start: "58. Al-Mujadilah Verse 1", end: "66. At-Tahrim Verse 12", juzArabicname: 'قَدْ سَمِعَ ٱللَّهُ'),
  JuzModel(juzNumber: 29, juzName: "Tabarakallazi", start: "67. Al-Mulk Verse 1", end: "77. Al-Mursalat Verse 50", juzArabicname: 'ِ تَبَٰرَكَ ٱلَّذِىٍۢ '),
  JuzModel(juzNumber: 30, juzName: "Amma Yatasa’aloon", start: "78. An-Naba Verse 1", end: "114. An-Nas Verse 6", juzArabicname: 'عَمَّ يَتَسَآءَلُونَ'),
];
