class AllahName {
  final int id;
  final String arabic;
  final String english;
  final String meaning;

  AllahName({
    required this.id,
    required this.arabic,
    required this.english,
    required this.meaning,
  });
}

final List<AllahName> AllahNames = [
  AllahName(id: 1, arabic: 'ٱلرَّحْمَـٰنُ', english: 'Ar-Rahman', meaning: 'The Beneficent'),
  AllahName(id: 2, arabic: 'ٱلرَّحِيمُ', english: 'Ar-Rahim', meaning: 'The Merciful'),
  AllahName(id: 3, arabic: 'ٱلْمَلِكُ', english: 'Al-Malik', meaning: 'The King'),
  AllahName(id: 4, arabic: 'ٱلْقُدُّوسُ', english: 'Al-Quddus', meaning: 'The Most Sacred'),
  AllahName(id: 5, arabic: 'ٱلسَّلَامُ', english: 'As-Salam', meaning: 'The Source of Peace, Safety'),
  AllahName(id: 6, arabic: 'ٱلْمُؤْمِنُ', english: 'Al-Mu’min', meaning: 'The Giver of Faith and Security'),
  AllahName(id: 7, arabic: 'ٱلْمُهَيْمِنُ', english: 'Al-Muhaymin', meaning: 'The Guardian, the Witness'),
  AllahName(id: 8, arabic: 'ٱلْعَزِيزُ', english: 'Al-Aziz', meaning: 'The Almighty'),
  AllahName(id: 9, arabic: 'ٱلْجَبَّارُ', english: 'Al-Jabbar', meaning: 'The Compeller'),
  AllahName(id: 10, arabic: 'ٱلْمُتَكَبِّرُ', english: 'Al-Mutakabbir', meaning: 'The Supreme'),
  AllahName(id: 11, arabic: 'ٱلْخَالِقُ', english: 'Al-Khaliq', meaning: 'The Creator'),
  AllahName(id: 12, arabic: 'ٱلْبَارِئُ', english: 'Al-Bari', meaning: 'The Evolver'),
  AllahName(id: 13, arabic: 'ٱلْمُصَوِّرُ', english: 'Al-Musawwir', meaning: 'The Fashioner'),
  AllahName(id: 14, arabic: 'ٱلْغَفَّارُ', english: 'Al-Ghaffar', meaning: 'The Constant Forgiver'),
  AllahName(id: 15, arabic: 'ٱلْقَهَّارُ', english: 'Al-Qahhar', meaning: 'The All-Subduer'),
  AllahName(id: 16, arabic: 'ٱلْوَهَّابُ', english: 'Al-Wahhab', meaning: 'The Supreme Bestower'),
  AllahName(id: 17, arabic: 'ٱلرَّزَّاقُ', english: 'Ar-Razzaq', meaning: 'The Provider'),
  AllahName(id: 18, arabic: 'ٱلْفَتَّاحُ', english: 'Al-Fattah', meaning: 'The Supreme Opener'),
  AllahName(id: 19, arabic: 'ٱلْعَلِيمُ', english: 'Al-‘Aleem', meaning: 'The All-Knowing'),
  AllahName(id: 20, arabic: 'ٱلْقَابِضُ', english: 'Al-Qaabid', meaning: 'The Withholder'),
  AllahName(id: 21, arabic: 'ٱلْبَاسِطُ', english: 'Al-Baasit', meaning: 'The Extender'),
  AllahName(id: 22, arabic: 'ٱلْخَافِضُ', english: 'Al-Khaafid', meaning: 'The Reducer'),
  AllahName(id: 23, arabic: 'ٱلرَّافِعُ', english: 'Ar-Rafi’', meaning: 'The Exalter'),
  AllahName(id: 24, arabic: 'ٱلْمُعِزُّ', english: 'Al-Mu’izz', meaning: 'The Honourer'),
  AllahName(id: 25, arabic: 'ٱلْمُذِلُّ', english: 'Al-Mudhill', meaning: 'The Dishonourer'),
  AllahName(id: 26, arabic: 'ٱلسَّمِيعُ', english: 'As-Sami’,', meaning: 'The All-Hearing'),
  AllahName(id: 27, arabic: 'ٱلْبَصِيرُ', english: 'Al-Baseer', meaning: 'The All-Seeing'),
  AllahName(id: 28, arabic: 'ٱلْحَكَمُ', english: 'Al-Hakam', meaning: 'The Impartial Judge'),
  AllahName(id: 29, arabic: 'ٱلْعَدْلُ', english: 'Al-‘Adl', meaning: 'The Utterly Just'),
  AllahName(id: 30, arabic: 'ٱللَّطِيفُ', english: 'Al-Lateef', meaning: 'The Subtle One'),
  AllahName(id: 31, arabic: 'ٱلْخَبِيرُ', english: 'Al-Khabeer', meaning: 'The All-Aware'),
  AllahName(id: 32, arabic: 'ٱلْحَلِيمُ', english: 'Al-Haleem', meaning: 'The Most Forbearing'),
  AllahName(id: 33, arabic: 'ٱلْعَظِيمُ', english: 'Al-‘Azeem', meaning: 'The Magnificent'),
  AllahName(id: 34, arabic: 'ٱلْغَفُورُ', english: 'Al-Ghafoor', meaning: 'The Great Forgiver'),
  AllahName(id: 35, arabic: 'ٱلشَّكُورُ', english: 'Ash-Shakoor', meaning: 'The Most Appreciative'),
  AllahName(id: 36, arabic: 'ٱلْعَلِيُّ', english: 'Al-‘Aliyy', meaning: 'The Most High'),
  AllahName(id: 37, arabic: 'ٱلْكَبِيرُ', english: 'Al-Kabeer', meaning: 'The Most Great'),
  AllahName(id: 38, arabic: 'ٱلْحَفِيظُ', english: 'Al-Hafiz', meaning: 'The Preserver'),
  AllahName(id: 39, arabic: 'ٱلْمُقِيتُ', english: 'Al-Muqeet', meaning: 'The Sustainer'),
  AllahName(id: 40, arabic: 'ٱلْحسِيبُ', english: 'Al-Haseeb', meaning: 'The Reckoner'),
  AllahName(id: 41, arabic: 'ٱلْجَلِيلُ', english: 'Al-Jaleel', meaning: 'The Majestic'),
  AllahName(id: 42, arabic: 'ٱلْكَرِيمُ', english: 'Al-Kareem', meaning: 'The Most Generous, the Most Esteemed'),
  AllahName(id: 43, arabic: 'ٱلرَّقِيبُ', english: 'Ar-Raqeeb', meaning: 'The Watchful'),
  AllahName(id: 44, arabic: 'ٱلْمُجِيبُ', english: 'Al-Mujeeb', meaning: 'The Responsive One'),
  AllahName(id: 45, arabic: 'ٱلْوَاسِعُ', english: 'Al-Waasi’', meaning: 'The All-Encompassing, the Boundless'),
  AllahName(id: 46, arabic: 'ٱلْحَكِيمُ', english: 'Al-Hakeem', meaning: 'The All-Wise'),
  AllahName(id: 47, arabic: 'ٱلْوَدُودُ', english: 'Al-Wadud', meaning: 'The Most Loving'),
  AllahName(id: 48, arabic: 'ٱلْمَجِيدُ', english: 'Al-Majeed', meaning: 'The Glorious, the Most Honorable'),
  AllahName(id: 49, arabic: 'ٱلْبَاعِثُ', english: 'Al-Ba’ith', meaning: 'The Infuser of New Life'),
  AllahName(id: 50, arabic: 'ٱلشَّهِيدُ', english: 'Ash-Shaheed', meaning: 'The All-and-Ever Witnessing'),
  AllahName(id: 51, arabic: 'ٱلْحَقُ', english: 'Al-Haqq', meaning: 'The Absolute Truth'),
  AllahName(id: 52, arabic: 'ٱلْوَكِيلُ', english: 'Al-Wakeel', meaning: 'The Trustee, the Disposer of Affairs'),
  AllahName(id: 53, arabic: 'ٱلْقَوِيُ', english: 'Al-Qawiyy', meaning: 'The All-Strong'),
  AllahName(id: 54, arabic: 'ٱلْمَتِينُ', english: 'Al-Matin', meaning: 'The Firm One'),
  AllahName(id: 55, arabic: 'ٱلْوَلِيُ', english: 'Al-Waliyy', meaning: 'The Sole Provider'),
  AllahName(id: 56, arabic: 'ٱلْحَمِيدُ', english: 'Al-Hameed', meaning: 'The Praiseworthy'),
  AllahName(id: 57, arabic: 'ٱلْمُحْصِي', english: 'Al-Muhsi', meaning: 'The All-Enumerating, the Counter'),
  AllahName(id: 58, arabic: 'ٱلْمُبْدِئُ', english: 'Al-Mubdi’,', meaning: 'The Originator, the Initiator'),
  AllahName(id: 59, arabic: 'ٱلْمُعِيدُ', english: 'Al-Mueed', meaning: 'The Restorer, the Reinstater'),
  AllahName(id: 60, arabic: 'ٱلْمُحْيِي', english: 'Al-Muhyi', meaning: 'The Giver of Life'),
  AllahName(id: 61, arabic: 'ٱلْمُمِيتُ', english: 'Al-Mumeet', meaning: 'The Creator of Death'),
  AllahName(id: 62, arabic: 'ٱلْحَيُ', english: 'Al-Hayy', meaning: 'The Ever-Living'),
  AllahName(id: 63, arabic: 'ٱلْقَيُّومُ', english: 'Al-Qayyoom', meaning: 'The Sustainer, The Self-Subsisting'),
  AllahName(id: 64, arabic: 'ٱلْوَاجِدُ', english: 'Al-Waajid', meaning: 'The Perceiver'),
  AllahName(id: 65, arabic: 'ٱلْمَاجِدُ', english: 'Al-Maajid', meaning: 'The Glorious, the Most Honorable'),
  AllahName(id: 66, arabic: 'ٱلْواحِدُ', english: 'Al-Waahid', meaning: 'The One'),
  AllahName(id: 67, arabic: 'ٱلْأَحَدُ', english: 'Al-Ahad', meaning: 'The Indivisible, the Absolute'),
  AllahName(id: 68, arabic: 'ٱلصَّمَدُ', english: 'As-Samad', meaning: 'The Self-Sufficient, the Impregnable'),
  AllahName(id: 69, arabic: 'ٱلْقَادِرُ', english: 'Al-Qaadir', meaning: 'The Omnipotent'),
  AllahName(id: 70, arabic: 'ٱلْمُقْتَدِرُ', english: 'Al-Muqtadir', meaning: 'The Creator of All Power'),
  AllahName(id: 71, arabic: 'ٱلْمُقَدِّمُ', english: 'Al-Muqaddim', meaning: 'The Expediter'),
  AllahName(id: 72, arabic: 'ٱلْمُؤَخِّرُ', english: 'Al-Mu’akhkhir', meaning: 'The Delayer'),
  AllahName(id: 73, arabic: 'ٱلأوَّلُ', english: 'Al-Awwal', meaning: 'The First'),
  AllahName(id: 74, arabic: 'ٱلْآخِرُ', english: 'Al-Aakhir', meaning: 'The Last'),
  AllahName(id: 75, arabic: 'ٱلظَّاهِرُ', english: 'Az-Zaahir', meaning: 'The Manifest'),
  AllahName(id: 76, arabic: 'ٱلْبَاطِنُ', english: 'Al-Baatin', meaning: 'The Hidden One, Knower of the Hidden'),
  AllahName(id: 77, arabic: 'ٱلْوَالِي', english: 'Al-Waali', meaning: 'The Sole Governor'),
  AllahName(id: 78, arabic: 'ٱلْمُتَعَالِي', english: 'Al-Muta’ali', meaning: 'The Self Exalted'),
  AllahName(id: 79, arabic: 'ٱلْبَرُّ', english: 'Al-Barr', meaning: 'The Source of All Goodness'),
  AllahName(id: 80, arabic: 'ٱلتَّوَابُ', english: 'At-Tawwaab', meaning: 'The Ever-Accepter of Repentance'),
  AllahName(id: 81, arabic: 'ٱلْمُنْتَقِمُ', english: 'Al-Muntaqim', meaning: 'The Avenger'),
  AllahName(id: 82, arabic: 'ٱلْعَفُوُ', english: 'Al-‘Afuww', meaning: 'The Supreme Pardoner'),
  AllahName(id: 83, arabic: 'ٱلرَّؤُوفُ', english: 'Ar-Ra’oof', meaning: 'The Most Kind'),
  AllahName(id: 84, arabic: 'مَالِكُ ٱلْمُلْكُ', english: 'Maalik-ul-Mulk', meaning: 'Master and King of the Kingdom'),
  AllahName(id: 85, arabic: 'ذُوٱلْجَلَالِ وَٱلْإِكْرَامِ', english: 'Dhul-Jalaali Wal-Ikraam', meaning: 'Lord of Glory and Honour'),
  AllahName(id: 86, arabic: 'ٱلْمُقْسِطُ', english: 'Al-Muqsit', meaning: 'The Just One'),
  AllahName(id: 87, arabic: 'ٱلْجَامِعُ', english: 'Al-Jaami’', meaning: 'The Gatherer, the Uniter'),
  AllahName(id: 88, arabic: 'ٱلْغَنيُ', english: 'Al-Ghaniyy', meaning: 'The Self-Sufficient, the Wealthy'),
  AllahName(id: 89, arabic: 'ٱلْمُغْنِيُ', english: 'Al-Mughni', meaning: 'The Enricher'),
  AllahName(id: 90, arabic: 'ٱلْمَانِعُ', english: 'Al-Maani’', meaning: 'The Withholder'),
  AllahName(id: 91, arabic: 'ٱلضَّارَ', english: 'Ad-Daarr', meaning: 'The Distresser'),
  AllahName(id: 92, arabic: 'ٱلنَّافِعُ', english: 'An-Naafi’', meaning: 'The Propitious, the Benefactor'),
  AllahName(id: 93, arabic: 'ٱلنُّورُ', english: 'An-Noor', meaning: 'The Light, the Illuminator'),
  AllahName(id: 94, arabic: 'ٱلْهَادِي', english: 'Al-Haadi', meaning: 'The Guide'),
  AllahName(id: 95, arabic: 'ٱلْبَدِيعُ', english: 'Al-Badee’', meaning: 'The Incomparable Originator'),
  AllahName(id: 96, arabic: 'ٱلْبَاقِي', english: 'Al-Baaqi', meaning: 'The Everlasting'),
  AllahName(id: 97, arabic: 'ٱلْوَارِثُ', english: 'Al-Waarith', meaning: 'The Inheritor, the Heir'),
  AllahName(id: 98, arabic: 'ٱلرَّشِيدُ', english: 'Ar-Rasheed', meaning: 'The Guide, Infallible Teacher and Knower'),
  AllahName(id: 99, arabic: 'ٱلصَّبُورُ', english: 'As-Saboor', meaning: 'The Most Patient'),

];
