class ProphetName {
  final int id;
  final String arabic;
  final String meaning;
  final String english;

  ProphetName({
    required this.id,
    required this.arabic,
    required this.meaning,
    required this.english
  });
}
final List<ProphetName> ProphetNames = [
  ProphetName(id: 1, arabic: 'مُحَمَّدٌ', english: 'Muhammad', meaning: 'The Praised One'),
  ProphetName(id: 2, arabic: 'أَحْمَدٌ', english: 'Ahmad', meaning: 'The Most Commendable'),
  ProphetName(id: 3, arabic: 'الْمُتَوَكِّلُ', english: 'Al-Mutawakkil', meaning: 'The One Who Relies on Allah'),
  ProphetName(id: 4, arabic: 'الْمَاحِي', english: 'Al-Mahi', meaning: 'The Eraser of Disbelief'),
  ProphetName(id: 5, arabic: 'الْحَاشِرُ', english: 'Al-Hashir', meaning: 'The Gatherer'),
  ProphetName(id: 6, arabic: 'الْعَاقِبُ', english: 'Al-Aqib', meaning: 'The Last (of the Prophets)'),
  ProphetName(id: 7, arabic: 'الْمُقَفِّي', english: 'Al-Muqaffi', meaning: 'The Successor (to the previous prophets)'),
  ProphetName(id: 8, arabic: 'نَبِيُّ التَّوْبَةِ', english: 'Nabiyyut-Tawbah', meaning: 'Prophet of Repentance'),
  ProphetName(id: 9, arabic: 'نَبِيُّ الرَّحْمَةِ', english: 'Nabiyyur-Rahmah', meaning: 'Prophet of Mercy'),
  ProphetName(id: 10, arabic: 'نَبِيُّ الْمَلْحَمَةِ', english: 'Nabiyyul-Malhamah', meaning: 'Prophet of Battle'),
  ProphetName(id: 11, arabic: 'نَبِيُّ الرَّحْمَٰنِ', english: 'Nabiyyur-Rahman', meaning: 'Prophet of the Most Merciful'),
  ProphetName(id: 12, arabic: 'كَهْفُ الْوَرَى', english: 'Kahf al-Wara', meaning: 'Refuge of Mankind'),
  ProphetName(id: 13, arabic: 'سِرَاجٌ مُّنِيرٌ', english: 'Siraj Munir', meaning: 'Illuminating Lamp'),
  ProphetName(id: 14, arabic: 'رَؤُوفٌ رَّحِيمٌ', english: 'Ra’uf Rahim', meaning: 'Kind and Merciful'),
  ProphetName(id: 15, arabic: 'طَهَ', english: 'Taha', meaning: 'Pure, name of the Prophet ﷺ'),
  ProphetName(id: 16, arabic: 'يَس', english: 'Yasin', meaning: 'Name of the Prophet ﷺ'),
  ProphetName(id: 17, arabic: 'الْقَاسِمُ', english: 'Al-Qasim', meaning: 'The Distributor'),
  ProphetName(id: 18, arabic: 'الْأَمِينُ', english: 'Al-Ameen', meaning: 'The Trustworthy'),
  ProphetName(id: 19, arabic: 'الصَّادِقُ', english: 'As-Sadiq', meaning: 'The Truthful'),
  ProphetName(id: 20, arabic: 'الْمُصْطَفَى', english: 'Al-Mustafa', meaning: 'The Chosen One'),
  ProphetName(id: 21, arabic: 'الْمُجْتَبَى', english: 'Al-Mujtaba', meaning: 'The Selected'),
  ProphetName(id: 22, arabic: 'الْكَرِيمُ', english: 'Al-Karim', meaning: 'The Generous'),
  ProphetName(id: 23, arabic: 'الرَّؤُوفُ', english: 'Ar-Ra’uf', meaning: 'The Kind'),
  ProphetName(id: 24, arabic: 'الرَّحِيمُ', english: 'Ar-Rahim', meaning: 'The Merciful'),
  ProphetName(id: 25, arabic: 'السِّرَاجُ الْمُنِيرُ', english: 'As-Sirajul Munir', meaning: 'The Radiant Lamp'),
  ProphetName(id: 26, arabic: 'الْمُنْذِرُ', english: 'Al-Mundhir', meaning: 'The Warner'),
  ProphetName(id: 27, arabic: 'الدَّاعِي', english: 'Ad-Da’i', meaning: 'The Caller (to Allah)'),
  ProphetName(id: 28, arabic: 'النَّذِيرُ', english: 'An-Nazir', meaning: 'The Warner'),
  ProphetName(id: 29, arabic: 'الْمُبَشِّرُ', english: 'Al-Mubashshir', meaning: 'The Bearer of Good News'),
  ProphetName(id: 30, arabic: 'الْمُذَكِّرُ', english: 'Al-Mudhakkir', meaning: 'The Reminder'),
  ProphetName(id: 31, arabic: 'الْمُطَاعُ', english: 'Al-Muta’a', meaning: 'The Obeyed One'),
  ProphetName(id: 32, arabic: 'الصَّارِمُ', english: 'As-Sarim', meaning: 'The Sharp One'),
  ProphetName(id: 33, arabic: 'الْمُنِيرُ', english: 'Al-Munir', meaning: 'The Enlightening One'),
  ProphetName(id: 34, arabic: 'الْمَصْبَاحُ', english: 'Al-Misbah', meaning: 'The Lamp'),
  ProphetName(id: 35, arabic: 'الْمِهْرَاجُ', english: 'Al-Mihraj', meaning: 'The Ascender'),
  ProphetName(id: 36, arabic: 'الرُّوحُ', english: 'Ar-Ruh', meaning: 'The Spirit'),
  ProphetName(id: 37, arabic: 'الْمِفْتَاحُ', english: 'Al-Miftah', meaning: 'The Key'),
  ProphetName(id: 38, arabic: 'الْهَادِي', english: 'Al-Hadi', meaning: 'The Guide'),
  ProphetName(id: 39, arabic: 'الرَّشِيدُ', english: 'Ar-Rashid', meaning: 'The Rightly Guided'),
  ProphetName(id: 40, arabic: 'الْمُرْشِدُ', english: 'Al-Murshid', meaning: 'The Instructor'),
  ProphetName(id: 41, arabic: 'الشَّافِعُ', english: 'Ash-Shafi’', meaning: 'The Intercessor'),
  ProphetName(id: 42, arabic: 'الْمُشَفَّعُ', english: 'Al-Musaffaa', meaning: 'The One Whose Intercession is Accepted'),
  ProphetName(id: 43, arabic: 'الْمُقَدَّمُ', english: 'Al-Muqaddam', meaning: 'The One Sent Before Others'),
  ProphetName(id: 44, arabic: 'خَيْرُ الْخَلْقِ', english: 'Khair Al-Khalq', meaning: 'Best of Creation'),
  ProphetName(id: 45, arabic: 'سَيِّدُ الْمُرْسَلِينَ', english: 'Sayyidul Mursalin', meaning: 'Leader of the Messengers'),
  ProphetName(id: 46, arabic: 'إِمَامُ الْمُتَّقِينَ', english: 'Imamul Muttaqin', meaning: 'Leader of the God-Fearing'),
  ProphetName(id: 47, arabic: 'سَيِّدُ النَّاسِ', english: 'Sayyidun-Nas', meaning: 'Leader of People'),
  ProphetName(id: 48, arabic: 'سَيِّدُ الْوَلَدِ آدَمَ', english: 'Sayyidu Waladi Adam', meaning: 'Master of the Children of Adam'),
  ProphetName(id: 49, arabic: 'حَبِيبُ اللهِ', english: 'Habibullah', meaning: 'Beloved of Allah'),
  ProphetName(id: 50, arabic: 'صَفِيُّ اللهِ', english: 'Safiyyullah', meaning: 'Chosen One of Allah'),
  ProphetName(id: 51, arabic: 'رَسُولُ اللهِ', english: 'Rasulullah', meaning: 'Messenger of Allah'),
  ProphetName(id: 52, arabic: 'نَبِيُّ اللهِ', english: 'Nabiyyullah', meaning: 'Prophet of Allah'),
  ProphetName(id: 53, arabic: 'عَابِدٌ', english: 'Abid', meaning: 'Worshipper'),
  ProphetName(id: 54, arabic: 'زَاهِدٌ', english: 'Zahid', meaning: 'Ascetic'),
  ProphetName(id: 55, arabic: 'مُتَعَبِّدٌ', english: 'Mutaa’bid', meaning: 'Devout Worshipper'),
  ProphetName(id: 56, arabic: 'خَاتَمُ النَّبِيِّينَ', english: 'Khatamun Nabiyyin', meaning: 'Seal of the Prophets'),
  ProphetName(id: 57, arabic: 'شَفِيعٌ', english: 'Shafi’', meaning: 'Intercessor'),
  ProphetName(id: 58, arabic: 'مُشَفَّعٌ', english: 'Mushaffa’', meaning: 'One whose intercession is accepted'),
  ProphetName(id: 59, arabic: 'صَاحِبُ الشَّفَاعَةِ', english: 'Sahib Ash-Shafa’ah', meaning: 'Holder of Intercession'),
  ProphetName(id: 60, arabic: 'صَاحِبُ الحَوْضِ', english: 'Sahib Al-Hawd', meaning: 'Owner of the Pool'),
  ProphetName(id: 61, arabic: 'صَاحِبُ اللِّوَاءِ', english: 'Sahib Al-Liwa', meaning: 'Bearer of the Banner'),
  ProphetName(id: 62, arabic: 'إِمَامُ المُتَّقِينَ', english: 'Imam Al-Muttaqeen', meaning: 'Leader of the Pious'),
  ProphetName(id: 63, arabic: 'سَيِّدُ الوَلَدِ آدَم', english: 'Sayyid Walad Adam', meaning: 'Master of the Children of Adam'),
  ProphetName(id: 64, arabic: 'خَيْرُ خَلْقِ اللهِ', english: 'Khair Khalqillah', meaning: 'Best of God’s Creation'),
  ProphetName(id: 65, arabic: 'حَبِيبُ اللهِ', english: 'Habibullah', meaning: 'Beloved of Allah'),
  ProphetName(id: 66, arabic: 'صَفِيُّ اللهِ', english: 'Safiyyullah', meaning: 'Chosen One of Allah'),
  ProphetName(id: 67, arabic: 'نَبِيُّ الرَّحْمَةِ', english: 'Nabiyyur Rahmah', meaning: 'Prophet of Mercy'),
  ProphetName(id: 68, arabic: 'نَبِيُّ التَّوْبَةِ', english: 'Nabiyyut Tawbah', meaning: 'Prophet of Repentance'),
  ProphetName(id: 69, arabic: 'نَبِيُّ المَلْحَمَةِ', english: 'Nabiyyul Malhamah', meaning: 'Prophet of Battles'),
  ProphetName(id: 70, arabic: 'نَبِيُّ الرُّحْمَانِ', english: 'Nabiyyur Rahman', meaning: 'Prophet of the Most Merciful'),
  ProphetName(id: 71, arabic: 'خَلِيلُ الرَّحْمَٰنِ', english: 'Khalilur Rahman', meaning: 'Friend of the Merciful'),
  ProphetName(id: 72, arabic: 'كَلِيمُ اللهِ', english: 'Kalimullah', meaning: 'One Who Spoke to Allah'),
  ProphetName(id: 73, arabic: 'خَاتَمُ المُرْسَلِينَ', english: 'Khatam Al-Mursaleen', meaning: 'Seal of the Messengers'),
  ProphetName(id: 74, arabic: 'نُورٌ', english: 'Noor', meaning: 'Light'),
  ProphetName(id: 75, arabic: 'سِرَاجٌ مُنِيرٌ', english: 'Siraj Munir', meaning: 'Illuminating Lamp'),
  ProphetName(id: 76, arabic: 'مُبَشِّرٌ', english: 'Mubashir', meaning: 'Bringer of Good News'),
  ProphetName(id: 77, arabic: 'نَذِيرٌ', english: 'Nazeer', meaning: 'Warner'),
  ProphetName(id: 78, arabic: 'دَاعٍ إِلَى اللهِ', english: 'Da’i ilallah', meaning: 'Caller to Allah'),
  ProphetName(id: 79, arabic: 'ذِكْرُ اللهِ', english: 'Dhikrullah', meaning: 'Remembrance of Allah'),
  ProphetName(id: 80, arabic: 'عَبْدُ اللهِ', english: 'Abdullah', meaning: 'Servant of Allah'),
  ProphetName(id: 81, arabic: 'الصَّادِقُ', english: 'As-Sadiq', meaning: 'The Truthful'),
  ProphetName(id: 82, arabic: 'الأَمِينُ', english: 'Al-Ameen', meaning: 'The Trustworthy'),
  ProphetName(id: 83, arabic: 'المَأْمُونُ', english: 'Al-Ma’mun', meaning: 'The Trusted'),
  ProphetName(id: 84, arabic: 'الصَّافِي', english: 'As-Saafi', meaning: 'The Pure'),
  ProphetName(id: 85, arabic: 'الطَّاهِرُ', english: 'At-Tahir', meaning: 'The Clean One'),
  ProphetName(id: 86, arabic: 'المُزَكَّى', english: 'Al-Muzakka', meaning: 'The Purified'),
  ProphetName(id: 87, arabic: 'المُجَاهِدُ', english: 'Al-Mujahid', meaning: 'The Warrior'),
  ProphetName(id: 88, arabic: 'المُتَوَاضِعُ', english: 'Al-Mutawadhi',meaning: 'The Humble'),
  ProphetName(id: 89, arabic: 'المُتَبَسِّمُ', english: 'Al-Mutabasim', meaning: 'The Smiling One'),
  ProphetName(id: 90, arabic: 'المُبَارَكُ', english: 'Al-Mubarak', meaning: 'The Blessed'),
  ProphetName(id: 91, arabic: 'المَسْعُودُ', english: 'Al-Mas’ud', meaning: 'The Fortunate'),
  ProphetName(id: 92, arabic: 'المَرْضِيُّ', english: 'Al-Mardiyy', meaning: 'The Approved'),
  ProphetName(id: 93, arabic: 'المُحِبُّ', english: 'Al-Muhibb', meaning: 'The Loving'),
  ProphetName(id: 94, arabic: 'المَحْبُوبُ', english: 'Al-Mahbub', meaning: 'The Loved One'),
  ProphetName(id: 95, arabic: 'السَّاجِدُ', english: 'As-Sajid', meaning: 'The One who Prostrates'),
  ProphetName(id: 96, arabic: 'الرَّاكِعُ', english: 'Ar-Raki’', meaning: 'The One who Bows'),
  ProphetName(id: 97, arabic: 'القَائِمُ', english: 'Al-Qa’im', meaning: 'The Standing One'),
  ProphetName(id: 98, arabic: 'العَابِدُ', english: 'Al-Abid', meaning: 'The Devout'),
  ProphetName(id: 99, arabic: 'المُخْلِصُ', english: 'Al-Mukhlis', meaning: 'The Sincere'),


];


